export { embedText, embedTransaction, cosineSimilarity } from './embeddings'
export { upsertTransaction, queryTransactions, deleteUserTransactions } from './vectorStore'
export { routeIntent } from './agents/intentRouter'
export { analyseSpending } from './agents/spendingAnalyst'
export { forecastSpending } from './agents/forecaster'
export { checkAffordability } from './agents/affordabilityChecker'
export { reviewAnomalies } from './agents/anomalyReviewer'
export { adviseSavingsGoals } from './agents/savingsGoalAdvisor'
export { adviseHabit } from './agents/habitAdvisor'
export { synthesizeResponse } from './agents/synthesizer'
export { buildTruffleGraph } from './graph'
export { generateProactiveMessage } from './proactive'
export { chatModel, visionModel, groq } from './llm'
export { langfuse } from './langfuse'
export { getSpeechTone, getToneGuidance } from './toneDetection'
export type { SpeechTone } from './toneDetection'
export { buildSystemPrompt } from './chatSystemPrompt'
export { selectModel, routedGenerateText } from './router'
export { logEval, incrementUsage, getGlobalUsage } from './eval'
export type { Provider, TaskType, EvalLogEntry } from './types'
